// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcuvgvdncamgqcjnufby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjdXZndmRuY2FtZ3Fjam51ZmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDk5MDAsImV4cCI6MjA2NDQyNTkwMH0.lAxni3YSxOG26hn6uTainYJ0txQaS_DhcUx7V71Fj90";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);